# -*- coding: utf-8 -*-
"""Predict_VGG16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oR4dRAAfqJsCUUk7L8U_9hEvXhptdAKb
"""

from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np
from keras.applications.vgg16 import preprocess_input, decode_predictions
import numpy as np

model = load_model('/content/gdrive/MyDrive/Prediccion Cancer Pulmon con VGG16/model_vgg16.h5')
img = image.load_img('/content/gdrive/MyDrive/Dataset/Validacion/Copia de NORMAL2-IM-0381-0001.jpeg', target_size=(224,224) )
x=image.img_to_array(img)
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
classes = model.predict(img_data)
A = np.squeeze(np.asarray(classes))
if (A[1]==1):
     print('NORMAL') 
else:
     print ('CON CANCER')



"""# Nueva sección"""