# -*- coding: utf-8 -*-
"""predecir.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10-25CCScgGkhZ6RG-cOoBLq1ozNUQX5i
"""

import numpy as np
from keras.preprocessing.image import load_img, img_to_array
from keras.models import load_model

from google.colab import drive
drive.mount('/content/drive')

longitud, altura = 100, 100
modelo = '/content/drive/MyDrive/Dataset/modelo/modelo.h5'
pesos = '/content/drive/MyDrive/Dataset/modelo/pesos.h5'

cnn = load_model(modelo)
cnn.load_weights(pesos)

def predict(file):
	x = load_img(file, target_size = (longitud, altura))
	x = img_to_array(x)
	x = np.expand_dims(x, axis = 0)
	arreglo = cnn.predict(x)
	resultado = arreglo[0]
	respuesta = np.argmax(resultado)

	if respuesta == 0:
		print('Tiene cancer de pulmon')
	elif respuesta == 1:
		print('No tiene cancer de pulmon')

	return respuesta

predict('/content/drive/MyDrive/Dataset/Validacion/00013285_009.png')